---
# tasks/main.yml

- name: Crear estructura de directorios
  file:
    path: "/home/joaquinabal/UTNFRA_SO_2do_Parcial_Abal/UTN-FRA-SO_Examenes/202406/ansible/tmp/2do_parcial/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - alumno
    - equipo

- name: Generar archivo datos_alumno.txt
  template:
    src: datos_alumno.txt.j2
    dest: /home/joaquinabal/UTNFRA_SO_2do_Parcial_Abal/UTN-FRA-SO_Examenes/202406/ansible/tmp/2do_parcial/alumno/datos_alumno.txt

- name: Generar archivo datos_equipo.txt
  template:
    src: datos_equipo.txt.j2
    dest: /home/joaquinabal/UTNFRA_SO_2do_Parcial_Abal/UTN-FRA-SO_Examenes/202406/ansible/tmp/2do_parcial/equipo/datos_equipo.txt

- name: Configurar sudoers para 2PSupervisores
  lineinfile:
    path: /etc/sudoers
    line: "%2PSupervisores ALL=(ALL) NOPASSWD:ALL"
    state: present


